### ISSUE TITLE
How to display help for subcommand if usage is incorrect ?

### ISSUE THREAD

**Issue by stuaxo** [trentm/cmdln#36]
I've started writing some cmdln code, if the user misses and argument then I'd like to display the help for the subcommand being run, is there a way to do it ?

```
# melange.py

import cmdln
import sys

class Admin(cmdln.Cmdln):
    name="startproject"
    
    def do_startproject(self, subcmd, opts, projectname):
        """${cmd_name}: create new melange project

        ${cmd_usage}                            # (1)
        """
        print("startproject %s" % projectname)

def main():
    admin = Admin()
    sys.exit(admin.main())
```

At the moment if I run ```melange startproject helloworld``` it is fine, if I run ```melange startproject``` I get a ```TypeError```

```
melange startproject
Traceback (most recent call last):
  File "/mnt/data/home/stu/.virtualenvs/melange/bin/melange", line 9, in <module>
    load_entry_point('melange==0.0.1', 'console_scripts', 'melange')()
  File "/mnt/data/home/stu/projects/mine/melange/melange/admin/__init__.py", line 23, in main
    sys.exit(admin.main())
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 264, in main
    return self.cmd(args)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 287, in cmd
    retval = self.onecmd(argv)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 425, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 1126, in _dispatch_cmd
    return handler(argv[0], opts, *args)
TypeError: do_startproject() missing 1 required positional argument: 'projectname'
```

**Comment by trentm** [comment]
There is a python 3 vs 2 diff behaviour here. Using "melange.py":

```python
import cmdln
import sys

class Admin(cmdln.Cmdln):
    name="startproject"

    def do_startproject(self, subcmd, opts, projectname):
        """${cmd_name}: create new melange project

        ${cmd_usage}                            # (1)
        """
        print("startproject %s" % projectname)

def main():
    admin = Admin()
    sys.exit(admin.main())

main()
```

I get this behaviour:

```
$ PYTHONPATH=`pwd`/lib python2 melange.py startproject
startproject startproject: takes exactly 1 argument (0 given)
Try 'startproject help startproject' for info.

$ PYTHONPATH=`pwd`/lib python3 melange.py startproject
Traceback (most recent call last):
  File "melange.py", line 18, in <module>
    main()
  File "melange.py", line 16, in main
    sys.exit(admin.main())
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 264, in main
    return self.cmd(args)
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 287, in cmd
    retval = self.onecmd(argv)
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 425, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 1126, in _dispatch_cmd
    return handler(argv[0], opts, *args)
TypeError: do_startproject() missing 1 required positional argument: 'projectname'
```

Likely due to the error message sniffing (a total hack) in Cmdln's error handling.

**Comment by trentm** [comment]
FWIW, `${cmd_usage}` is also obviously wrong:

```
$ PYTHONPATH=`pwd`/lib python melange.py help startproject
startproject: create new melange project

Usage:
    startproject startproject PROJECTNAME

# (1)
```

You could open a separate bug on that.;)

**Comment by trentm** [comment]
One way to be able to handle incorrect args:

```
$ PYTHONPATH=`pwd`/lib python3 melange.py startproject
melange startproject: no projectname argument given
Try 'melange help startproject' for info.

$ PYTHONPATH=`pwd`/lib python3 melange.py startproject foo
startproject foo
```

Is with the subcmd def like this:

```python
    def do_startproject(self, subcmd, opts, *projectname):
        """${cmd_name}: create new melange project"""
        if not projectname:
            raise cmdln.CmdlnUserError('no projectname argument given')
        print("startproject %s" % projectname[0])
```

But then you have to check for multiple projectname args, you can't have others after. Not ideal.
You could fallback to raw handling (that doesn't handle opts) with:

```python
            def do_foo(self, argv):
                # 'argv' is the vector of command line args, argv[0] is
                # the command name itself (i.e. "foo" or an alias)
                pass
```

**Comment by trentm** [comment]
Fixed the v2/v3 diff mentioned above.

**Comment by stuaxo** [comment]
Ah, works better now with patch (+ I fixed the usage).    In the end I used ```projectname = None``` so I could have a custom hint if it was missing... (not sure if this will cause problems elsewhere, but seems to work) -

class Admin(cmdln.Cmdln):
    name="melange"
    
    @cmdln.option("-t", "--template",                     # (1)
                    help="which project template to use?")
    def do_startproject(self, subcmd, opts, projectname=None):
        """${cmd_name}: create new melange project

        ${cmd_usage}                            # (1)
        ${cmd_option_list}
        """
        if not projectname:
            raise cmdln.CmdlnUserError('projectname not specified')
        else:
            startproject(projectname, opts.template or "default")
```

**Comment by trentm** [comment]
Ah right, `arg=None` is a better answer here.
