### ISSUE TITLE
'help' in cmdloop in python 3 - fails

### ISSUE THREAD

**Issue by stuaxo** [trentm/cmdln#37]
I just tried cmdloop for the first time but I get an error when I type in 'help'

```
melange> h
unknown command: 'h'
melange> help
Traceback (most recent call last):
  File "/mnt/data/home/stu/.virtualenvs/melange/bin/melange", line 9, in <module>
    load_entry_point('melange==0.0.1', 'console_scripts', 'melange')()
  File "/mnt/data/home/stu/projects/mine/melange/melange/admin/__init__.py", line 59, in main
    admin.cmdloop()
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 359, in cmdloop
    retval = self.onecmd(argv)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 423, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 1108, in _dispatch_cmd
    return handler(argv)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 530, in do_help
    doc = self._help_preprocess(doc, cmdname)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 611, in _help_preprocess
    help = preprocessor(help, cmdname)
  File "/mnt/data/home/stu/.virtualenvs/melange/lib/python3.4/site-packages/cmdln.py", line 622, in _help_preprocess_option_list
    if self.optparser:
AttributeError: 'Admin' object has no attribute 'optparser'
```

**Comment by stuaxo** [comment]
help (someoption) works OK:
also normal options
```
melange> help run
run: create new melange project

Usage:
    melange run [PROJECTDIR]

# (1)
Options:
    -h, --help          show this help message and exit
    -c CLIENT, --client=CLIENT
                        which client to use?
melange> run
pyglet client OK
melange> 
```

**Comment by stuaxo** [comment]
Hi @trentm 
   Any chance this could get applied ?

Cheers
S
